package utils

const (
	E_unauthorized              = "unauthorized"
	E_invalid_token             = "invalid_token"
	E_invalid_sigature          = "invalid_signature"
	E_bad_request               = "bad_request"
	E_access_denied             = "access_is_denied"
	E_invalid_user              = "not_found_user"
	E_invalid_user_id           = "not_found_user_id"
	E_invalid_role              = "not_found_role"
	E_invalid_permission        = "not_found_permission"
	E_email_cannot_empty        = "email_cannot_empty"
	E_username_cannot_empty     = "username_cannot_empty"
	E_password_cannot_empty     = "password_cannot_empty"
	E_phone_number_cannot_empty = "phone_number_cannot_empty"
	E_role_cannot_empty         = "role_cannot_empty"
	E_invalid_username          = "invalid_username"
	E_invalid_email             = "invalid_email"
	E_not_found_password        = "invalid_password"
	E_not_found_role_id         = "invalid_role_id"
	E_internal_errors           = "internal_errors"
	E_name_cannot_empty         = "name_cannot_empty"
	E_full_name_cannot_empty    = "full_name_cannot_empty"
	E_user_existed              = "user_existed"
	E_not_found_code            = "not_found_code"
	E_not_found_item_cart       = "not_found_item_cart"
)
